all:
	@echo 'make in db directory: Please specify a target.'
	@echo '(Use 'build', not 'make', to update the current db with the latest move files)'

fullclean:
	@echo Removing: move.* db db.*
	rm -f move.*
	rm -f db db.*
